sudo: false
language: node_js

matrix:
    include:
        - node_js: "4"
        - node_js: "5"
        - node_js: "6"
    allow_failures:
        - node_js: "0.10"
        - node_js: "0.11"
        - node_js: "0.12"

notifications:
    email: false
